# Generated by Django 4.2.7 on 2023-11-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterField(
            model_name='summary',
            name='generated_file',
            field=models.FileField(blank=True, default=None, upload_to='files/generated/'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='generated_text',
            field=models.TextField(blank=True),
        ),
    ]
