# Generated by Django 4.2.7 on 2023-11-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_summary_options_alter_summary_generated_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='input_file',
            field=models.FileField(blank=True, default=None, upload_to='files/input/'),
        ),
    ]
